- id: check-app-readme
  always_run: true
  description: Check date and any other issues with App README.md file before commit.
  entry: check-app-readme
  files: 'README.md'
  language: python
  name: Check App README.md
  pass_filenames: false
